<a href="https://colab.research.google.com/github/avinash-betha/crop-recommendation/blob/master/crop_recommondation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, LearningRateScheduler
from tensorflow.keras import optimizers
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Step 1: Load the data
data = pd.read_csv('/content/Crop_recommendation.csv')
data.head()


N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
# Step 2: Split the data into features and labels
X = data.drop('label', axis=1)
y = data['label']

# Encode labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [ ]:
# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
# Step 4: Preprocess the data (standardization in this case)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Step 5: Build a model (Neural Network in this case)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(len(label_encoder.classes_), activation='softmax')  # Use the number of classes
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [ ]:
# Step 6: Train the model with early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

model.fit(X_train_scaled, y_train, epochs=50, batch_size=32,
          validation_data=(X_test_scaled, y_test), callbacks=[early_stopping])


Epoch 1/50
55/55 [==============================] - 1s 7ms/step - loss: 2.5025 - accuracy: 0.3824 - val_loss: 1.8523 - val_accuracy: 0.5864
Epoch 2/50
55/55 [==============================] - 0s 4ms/step - loss: 1.3091 - accuracy: 0.7483 - val_loss: 0.9037 - val_accuracy: 0.7909
Epoch 3/50
55/55 [==============================] - 0s 3ms/step - loss: 0.6333 - accuracy: 0.8784 - val_loss: 0.4922 - val_accuracy: 0.8955
Epoch 4/50
55/55 [==============================] - 0s 4ms/step - loss: 0.3769 - accuracy: 0.9256 - val_loss: 0.3455 - val_accuracy: 0.9227
Epoch 5/50
55/55 [==============================] - 0s 3ms/step - loss: 0.2663 - accuracy: 0.9426 - val_loss: 0.2668 - val_accuracy: 0.9295
Epoch 6/50
55/55 [==============================] - 0s 3ms/step - loss: 0.2056 - accuracy: 0.9580 - val_loss: 0.2325 - val_accuracy: 0.9250
Epoch 7/50
55/55 [==============================] - 0s 4ms/step - loss: 0.1690 - accuracy: 0.9608 - val_loss: 0.1966 - val_accuracy: 0.9545
Epoch 8/50
55/55 [==

In [ ]:
# Step 7: Evaluate the model
y_pred = model.predict(X_test_scaled)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_orig = label_encoder.inverse_transform(y_test)
y_pred_orig = label_encoder.inverse_transform(y_pred_classes)
accuracy = accuracy_score(y_test_orig, y_pred_orig)

# Print the confusion matrix
conf_matrix = confusion_matrix(y_test_orig, y_pred_orig, labels=label_encoder.classes_)
print("Confusion Matrix:")
print(conf_matrix)

# Calculate accuracy
print(f'Accuracy: {accuracy}')


14/14 [==============================] - 0s 2ms/step
Confusion Matrix:
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 16  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 

In [ ]:
# Step 8: Save the model
model.save('/content/model/crop_model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
# Step 9: Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('crop_model.tflite', 'wb') as f:
    f.write(tflite_model)

In [ ]:
# the code for checking input and output details
interpreter = lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Get input details
input_details = interpreter.get_input_details()
print("Input details:", input_details)

# Get output details
output_details = interpreter.get_output_details()
print("Output details:", output_details)


Input details: [{'name': 'serving_default_dense_23_input:0', 'index': 0, 'shape': array([1, 7], dtype=int32), 'shape_signature': array([-1,  7], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Output details: [{'name': 'StatefulPartitionedCall:0', 'index': 10, 'shape': array([ 1, 22], dtype=int32), 'shape_signature': array([-1, 22], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]


In [ ]:
# The sample input data
sample_input = np.array([[28, 58, 24, 19.72703, 18.28173, 5.74819, 143.7631]], dtype=np.float32)


In [ ]:
# Load the TensorFlow Lite model
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Set input tensor
input_tensor_index = interpreter.get_input_details()[0]['index']
interpreter.tensor(input_tensor_index)()[0] = sample_input

# Run inference
interpreter.invoke()

# Get the output tensor
output_tensor_index = interpreter.get_output_details()[0]['index']
tflite_output = interpreter.tensor(output_tensor_index)()
